### ISSUE TITLE
必要なテストの洗い出し、作成

### ISSUE THREAD

**Issue by ikepon** [ikepon/isetan#19]
- [x] ある程度で来た段階でテストを書いているか、妥当なテストかを確認
- [x] 必要な箇所はテストを作成する
  - [x] login周り
  - [x] 登録ページ
  - [x] TOPページ
  - 感想ページ
    - [x] 一覧ページ
    - [x] 詳細ページ
    - [x] 新しい感想を書く
    - [x] 編集ページ
  - 蔵書ページ
    - [x] 一覧ページ
    - [x] 詳細ページ
    - [x] 新しい蔵書登録
  - [x] お問合せ
  - Newsページ
    - [x] サイドバーの表示
    - [x] 一覧ページ
    - [x] 詳細ページ
  - ユーザー
    - [x] 一覧ページ
    - [x] 詳細ページ
    - [x] プロフィール編集

**Comment by ikepon** [comment]
早めにテストかかんとバグがヤバイ。。。

**Comment by akirakudo** [comment]
:+1:

**Comment by ikepon** [comment]
テスト書いていく中でバグの多さにビックリ。。。
テストって大事だな。。。
